In [1]:
import pandas as pd

titanic_data = pd.read_csv('./data/Titanic-Dataset.csv')

In [2]:
titanic_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [3]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
titanic_data.drop(['PassengerId', 'Name', 'Ticket', 'SibSp', 'Parch', 'Cabin', 'Embarked'], axis='columns', inplace=True)

In [5]:
titanic_data.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [6]:
target = titanic_data['Survived']
input_data = titanic_data.drop(['Survived'], axis='columns')

In [7]:
dumies = pd.get_dummies(input_data.Sex).astype(int)
dumies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [8]:
input_data = pd.concat([input_data.drop('Sex', axis=1), dumies], axis=1)
input_data.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [9]:
# tell you which columns has na (empty) value in your table
input_data.columns[input_data.isna().any()]

Index(['Age'], dtype='object')

In [10]:
input_data.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [11]:
# fill empty cells with mean of that column
input_data.Age = input_data.Age.fillna(input_data.Age.mean())
input_data.head(10)

   Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1
6       1  54.000000  51.8625       0     1
7       3   2.000000  21.0750       0     1
8       3  27.000000  11.1333       1     0
9       2  14.000000  30.0708       1     0

In [29]:
# split our data to training and testing data
from sklearn.model_selection import train_test_split
# train data size = 80 % while testing data size = 20 %
X_train, X_test, y_train, y_test = train_test_split(input_data, target, test_size=0.2)

In [13]:
len(X_train)

712

In [14]:
len(y_test)

179

In [15]:
# import the model from sklearn and then greate
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [30]:
model.fit(X_train, y_train)

GaussianNB()

In [31]:
model.score(X_test, y_test)

0.776536312849162

In [32]:
X_test[:10]

     Pclass        Age      Fare  female  male
315       3  26.000000    7.8542       1     0
884       3  25.000000    7.0500       0     1
838       3  32.000000   56.4958       0     1
214       3  29.699118    7.7500       0     1
435       1  14.000000  120.0000       1     0
8         3  27.000000   11.1333       1     0
834       3  18.000000    8.3000       0     1
673       2  31.000000   13.0000       0     1
766       1  29.699118   39.6000       0     1
7         3   2.000000   21.0750       0     1

In [33]:
y_test[:10]

315    1
884    0
838    1
214    0
435    1
8      1
834    0
673    1
766    0
7      0
Name: Survived, dtype: int64

In [40]:
model.predict(X_test[:10])

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [38]:
# from sklearn.metrics import mean_absolute_error
# print(mean_absolute_error(y_test[:10], prediction))

0.2

In [39]:
model.predict_proba(X_test)

array([[8.07715337e-02, 9.19228466e-01],
       [9.90804770e-01, 9.19522961e-03],
       [9.82065743e-01, 1.79342567e-02],
       [9.91316254e-01, 8.68374602e-03],
       [5.50416388e-05, 9.99944958e-01],
       [8.29265892e-02, 9.17073411e-01],
       [9.89732377e-01, 1.02676232e-02],
       [9.80527938e-01, 1.94720616e-02],
       [9.08735836e-01, 9.12641640e-02],
       [9.83935613e-01, 1.60643871e-02],
       [9.91178451e-01, 8.82154932e-03],
       [9.90722977e-01, 9.27702344e-03],
       [9.10741820e-01, 8.92581798e-02],
       [9.91486680e-01, 8.51332024e-03],
       [9.85159997e-01, 1.48400027e-02],
       [6.26172770e-01, 3.73827230e-01],
       [4.97482878e-02, 9.50251712e-01],
       [9.90848491e-01, 9.15150904e-03],
       [9.80346720e-01, 1.96532802e-02],
       [9.91268691e-01, 8.73130930e-03],
       [9.25346505e-01, 7.46534947e-02],
       [3.33901302e-02, 9.66609870e-01],
       [9.87253953e-01, 1.27460473e-02],
       [8.55983656e-02, 9.14401634e-01],
       [3.58061261e-02, 9.64193874e-01],
       [9.91610597e-01, 8.38940281e-03],
       [9.90041182e-01, 9.95881751e-03],
       [9.89082798e-01, 1.09172024e-02],
       [9.20493479e-12, 1.00000000e+00],
       [9.91822193e-01, 8.17780690e-03],
       [6.94645919e-01, 3.05354081e-01],
       [1.62902484e-03, 9.98370975e-01],
       [9.88202682e-01, 1.17973176e-02],
       [9.89441772e-01, 1.05582283e-02],
       [9.90144581e-01, 9.85541943e-03],
       [7.52898433e-02, 9.24710157e-01],
       [9.90394499e-01, 9.60550126e-03],
       [9.68272873e-01, 3.17271272e-02],
       [9.91347787e-01, 8.65221322e-03],
       [1.44390963e-11, 1.00000000e+00],
       [9.90803735e-01, 9.19626476e-03],
       [8.55983656e-02, 9.14401634e-01],
       [9.91494807e-01, 8.50519315e-03],
       [9.22779094e-01, 7.72209062e-02],
       [9.90475401e-01, 9.52459874e-03],
       [9.90095770e-01, 9.90422994e-03],
       [5.07346088e-02, 9.49265391e-01],
       [1.67986181e-01, 8.32013819e-01],
       [6.82520696e-01, 3.17479304e-01],
       [9.91315064e-01, 8.68493552e-03],
       [8.56380595e-01, 1.43619405e-01],
       [3.21065615e-02, 9.67893439e-01],
       [8.13624486e-02, 9.18637551e-01],
       [8.29311976e-02, 9.17068802e-01],
       [9.91203759e-01, 8.79624145e-03],
       [9.89267056e-01, 1.07329445e-02],
       [9.89821807e-01, 1.01781933e-02],
       [9.91285404e-01, 8.71459650e-03],
       [9.91180822e-01, 8.81917797e-03],
       [3.58925089e-02, 9.64107491e-01],
       [9.14328298e-01, 8.56717025e-02],
       [4.13152329e-07, 9.99999587e-01],
       [9.91333018e-01, 8.66698199e-03],
       [9.25295414e-01, 7.47045865e-02],
       [9.91522248e-01, 8.47775214e-03],
       [9.91180448e-01, 8.81955200e-03],
       [9.89339080e-01, 1.06609202e-02],
       [2.60160352e-51, 1.00000000e+00],
       [9.91324493e-01, 8.67550715e-03],
       [9.90600049e-01, 9.39995146e-03],
       [5.05922858e-03, 9.94940771e-01],
       [3.46298354e-02, 9.65370165e-01],
       [9.80227300e-01, 1.97726995e-02],
       [9.91355364e-01, 8.64463569e-03],
       [9.81022423e-01, 1.89775769e-02],
       [9.77886902e-01, 2.21130983e-02],
       [9.91521672e-01, 8.47832770e-03],
       [7.98376565e-02, 9.20162343e-01],
       [9.91355611e-01, 8.64438903e-03],
       [7.90533429e-15, 1.00000000e+00],
       [3.40636741e-02, 9.65936326e-01],
       [9.76612467e-01, 2.33875326e-02],
       [9.89604123e-01, 1.03958766e-02],
       [9.27477396e-01, 7.25226037e-02],
       [8.07403872e-12, 1.00000000e+00],
       [9.91281207e-01, 8.71879324e-03],
       [1.64522206e-03, 9.98354778e-01],
       [9.81449696e-01, 1.85503035e-02],
       [9.91315299e-01, 8.68470077e-03],
       [7.73327791e-02, 9.22667221e-01],
       [7.52433585e-02, 9.24756642e-01],
       [9.91309391e-01, 8.69060892e-03],
       [9.91316254e-01, 8.68374602e-03],
       [9.91267945e-01, 8.73205539e-03],
       [9.78277155e-01, 2.17228448e-02],
       [9.77717335e-03, 9.90222827e-01],
       [9.91180822e-01, 8.81917797e-03],
       [8.36188083e-02, 9.16381192e-01],
       [9.91285146e-01, 8.71485436e-03],
       [9.90943650e-01, 9.05635004e-03],
       [9.91476509e-01, 8.52349065e-03],
       [9.89538004e-01, 1.04619957e-02],
       [1.57878670e-02, 9.84212133e-01],
       [3.94577184e-02, 9.60542282e-01],
       [6.52996562e-01, 3.47003438e-01],
       [9.90850491e-01, 9.14950853e-03],
       [8.72627312e-02, 9.12737269e-01],
       [9.91333018e-01, 8.66698199e-03],
       [9.91656849e-01, 8.34315102e-03],
       [9.90738097e-01, 9.26190347e-03],
       [9.91260399e-01, 8.73960069e-03],
       [9.81327418e-01, 1.86725822e-02],
       [9.24638252e-01, 7.53617479e-02],
       [7.27944426e-02, 9.27205557e-01],
       [9.90396187e-01, 9.60381340e-03],
       [9.81004025e-01, 1.89959746e-02],
       [9.91636497e-01, 8.36350258e-03],
       [9.91317679e-01, 8.68232100e-03],
       [5.86677055e-02, 9.41332294e-01],
       [9.76984656e-01, 2.30153440e-02],
       [9.90100287e-01, 9.89971330e-03],
       [3.15746105e-02, 9.68425390e-01],
       [3.38480886e-02, 9.66151911e-01],
       [4.73054974e-02, 9.52694503e-01],
       [8.25320123e-02, 9.17467988e-01],
       [9.90728992e-01, 9.27100834e-03],
       [9.91355611e-01, 8.64438903e-03],
       [9.91367455e-01, 8.63254538e-03],
       [8.48942319e-02, 9.15105768e-01],
       [3.10492046e-02, 9.68950795e-01],
       [8.05655151e-03, 9.91943448e-01],
       [9.91324493e-01, 8.67550715e-03],
       [6.40937380e-03, 9.93590626e-01],
       [8.55675658e-02, 9.14432434e-01],
       [8.59199804e-02, 9.14080020e-01],
       [7.44286492e-02, 9.25571351e-01],
       [9.80050138e-01, 1.99498623e-02],
       [7.65014526e-02, 9.23498547e-01],
       [9.90188842e-01, 9.81115766e-03],
       [1.59225507e-03, 9.98407745e-01],
       [8.75807319e-01, 1.24192681e-01],
       [7.27962306e-02, 9.27203769e-01],
       [9.89354538e-01, 1.06454620e-02],
       [9.80809617e-01, 1.91903827e-02],
       [8.37219134e-02, 9.16278087e-01],
       [9.90681475e-01, 9.31852512e-03],
       [9.77621065e-01, 2.23789345e-02],
       [9.90618456e-01, 9.38154372e-03],
       [2.88275622e-02, 9.71172438e-01],
       [9.91261439e-01, 8.73856144e-03],
       [9.90414106e-01, 9.58589362e-03],
       [9.90232070e-01, 9.76793007e-03],
       [9.91840455e-01, 8.15954540e-03],
       [9.91217884e-01, 8.78211613e-03],
       [9.61945758e-01, 3.80542419e-02],
       [9.91522823e-01, 8.47717694e-03],
       [9.78723010e-01, 2.12769904e-02],
       [7.61165561e-02, 9.23883444e-01],
       [8.37436955e-02, 9.16256305e-01],
       [9.80015953e-01, 1.99840473e-02],
       [5.51619904e-03, 9.94483801e-01],
       [3.62437237e-02, 9.63756276e-01],
       [8.34456000e-02, 9.16554400e-01],
       [4.50604988e-02, 9.54939501e-01],
       [2.39988634e-02, 9.76001137e-01],
       [9.19085161e-01, 8.09148392e-02],
       [8.53640657e-01, 1.46359343e-01],
       [9.25858467e-01, 7.41415327e-02],
       [9.76699968e-01, 2.33000321e-02],
       [8.77927544e-01, 1.22072456e-01],
       [9.80230130e-01, 1.97698699e-02],
       [9.90936663e-01, 9.06333715e-03],
       [9.81748975e-01, 1.82510246e-02],
       [6.85804280e-02, 9.31419572e-01],
       [9.90322716e-01, 9.67728414e-03],
       [8.43615265e-02, 9.15638473e-01],
       [9.91316254e-01, 8.68374602e-03],
       [9.91474217e-01, 8.52578318e-03],
       [3.46060513e-02, 9.65393949e-01]])